
code_syntax_highlight = "dracula"

# border
file_panel_border = "#39BAE6"
sidebar_border = "#FCFCFC"
footer_border = "#FFB454"


# ========= Border Active =========
file_panel_border_active = "#ff5555" # Lavendar
sidebar_border_active = "#ffb86c"    # Red
footer_border_active = "#14ff00"     # Green
modal_border_active = "#b4befe"      # Overlay2

# ========= Background (bg) =========
full_screen_bg = "#1e1e2e"
file_panel_bg = "#1e1e2e"
sidebar_bg = "#1e1e2e"
footer_bg = "#3D0301"
modal_bg = "#1e1e2e"

# ========= Foreground (fg) =========
full_screen_fg = "#f8f8f2"
file_panel_fg = "#f8f8f2"
sidebar_fg = "#f8f8f2"
footer_fg = "#f8f8f2"
modal_fg = "#f8f8f2"

# ========= Special Color =========
cursor = "#ff79c6"
correct = "#50fa7b"
error = "#ff5555"
hint = "#8be9fd"
cancel = "#6272a4"
# Gradient color can only have two color!
gradient_color = ["#50fa7b", "#ff5555"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#50fa7b"
file_panel_top_path = "#8be9fd"
file_panel_item_selected_fg = "#ffb86c"
file_panel_item_selected_bg = "#282a36"

# ========= Sidebar Special Items =========
sidebar_title = "#bd93f9"
sidebar_item_selected_fg = "#ffb86c"
sidebar_item_selected_bg = "#282a36"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#f8f8f2"
modal_cancel_bg = "#6272a4"

modal_confirm_fg = "#f8f8f2"
modal_confirm_bg = "#ffb86c"


# ========= Help Menu =========
help_menu_hotkey = "#ffb86c"
help_menu_title = "#bd93f9"
