
#Y: ================== Code Color ==============================
code_syntax_highlight = "dracula"


# Y: ================== Borders ================================
file_panel_border = "#00CA9a"
sidebar_border = "#1e1e2e"
footer_border = "#f5e0dc"

# ------- Active 
file_panel_border_active = "#F3C623" # file + active
sidebar_border_active = "#FE5D26"    # directory
footer_border_active = "#00CAFF"     # process meta
modal_border_active = "#ff0000"      # help menu

# EXTRAS:
# file_panel_border_active = "#ff5555" # Lavendar
# sidebar_border_active = "#ffb86c"    # Red
# footer_border_active = "#14ff00"     # Green
# modal_border_active = "#b4befe"      # Overlay2
# file_panel_border_active = "#00CAFF" # Lavendar
# ------------------------------------------------

#Y: ================== Background =============================
full_screen_bg = "#000000"
file_panel_bg = "#000000"
sidebar_bg = "#000000"
footer_bg = "#1e1e2e"
modal_bg = "#1e1e2e"

#Y: ================== TEXT: Foreground (fg) ==================
full_screen_fg = "#a6adc8"
file_panel_fg = "#FFFFFF"
sidebar_fg = "#FFFFFF"
footer_fg = "#a6adc8"
modal_fg = "#a6adc8"


#Y: ================== Special Color ==========================
cursor = "#14ff00"
correct = "#50fa7b"
error = "#ff5555"
hint = "#8be9fd"
cancel = "#6272a4"
# Gradient color can only have two color!
# gradient_color = ["#00FFDE", "#afff00", "#50fa7b", "#FE5D26", "#ff5555"]
gradient_color = ["#00FFDE", "#50fa7b"]

#Y: ========= File Panel Special Items =========
file_panel_top_directory_icon = "#FE5D26"
file_panel_top_path = "#00FFDE"
file_panel_item_selected_fg = "#afff00"
file_panel_item_selected_bg = "#1e1e2e"

#Y: ========= Sidebar Special Items =========
sidebar_title = "#ffb86c"
sidebar_item_selected_fg = "#afff00"
sidebar_item_selected_bg = "#1e1e2e"
sidebar_divider = "#14ff00"

#Y: ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = "#eba0ac"
modal_confirm_fg = "#383838"
modal_confirm_bg = "#89dceb"

#Y: ========= Help Menu =========
help_menu_hotkey = "#89dceb"
help_menu_title = "#eba0ac"
