
# IMP: NOTES:
# S => Style
# * Normal or Select mode hotkeys can conflict with other modes but cannot conflict with global hotkeys)

#Y: special keys
toggle_dot_file = ['.']
open_help_menu = ['?']
open_command_line = [':']
search_bar = ['/']

#R:normal keys=================================================================================================
copy_present_working_directory = ['c']
open_file_with_editor = ['e']
list_down = ['j']
list_up = ['k']
file_panel_item_create = ['n']         # crete file  - a
paste_items = ['p']                    # pest file
file_panel_item_rename = ['r']         # rename file - r
change_panel_mode = ['v']
cut_items = ['x']                      # cut file
copy_items = ['y']                     # copy file   

#G: normal + specila  =========================================================================================
delete_items = ['d', 'delete']                # delete file
parent_directory = ['h', 'left', 'backspace']
confirm = ['l', 'enter']
confirm_typing = ['enter']

#B: Shift======================================================================================================
file_panel_select_all_items = ['A']
open_current_directory_with_editor = ['E']
toggle_footer = ['F']
previous_file_panel = ['H']                                    # lazyvim S
file_panel_select_mode_items_select_down = ['J', 'shift+down']
file_panel_select_mode_items_select_up = ['K', 'shift+up']
next_file_panel = ['L']                                        # lazyvim S
create_new_file_panel = ['N']                                  # lazyvim S
quit = ['Q']

# Y: ctrl =====================================================================================================
compress_file = ['ctrl+a']            # archive
cancel_typing = ['ctrl+c', 'esc']
page_down = ['ctrl+d']                # pgdown
focus_on_metadata = ['ctrl+m']        # lazyvim S
focus_on_process_bar = ['ctrl+p']     # lazyvim S
focus_on_sidebar = ['ctrl+s']         # lazyvim S
page_up = ['ctrl+u']                  # pgup
close_file_panel = ['ctrl+w']         # browser S
extract_file = ['ctrl+x']             # eXtract
copy_path = ['ctrl+y']
pinned_directory = ['alt+P']
open_sort_options_menu = ['alt+s']
toggle_file_preview_panel = ['alt+f'] # lazyvim S
toggle_reverse_sort = ['alt+r']


#Y: special keys
#    toggle_dot_file =     ['.']
#    open_help_menu =      ['?']
#    open_command_line =   [':']
#    search_bar =          ['/']
#
#R:normal keys=================================================================================================
# copy_present_working_directory = ['c']
# open_file_with_editor =          ['e']
# list_down =                      ['j']
# list_up =                        ['k']
# file_panel_item_create =         ['n'] # crete file  - a
# paste_items =                    ['p'] # pest file
# file_panel_item_rename =         ['r'] # rename file - r
# change_panel_mode =              ['v']
# cut_items =                      ['x'] # cut file
# copy_items =                     ['y'] # copy file   
#
#G: normal + specila  =========================================================================================
# delete_items =     ['d', 'delete'] # delete file
# parent_directory = ['h', 'left', 'backspace']
# confirm =          ['l', 'enter']
# confirm_typing =   ['enter']
#
#B: Shift======================================================================================================
# file_panel_select_all_items =              ['A']
# open_current_directory_with_editor =       ['E']
# toggle_footer =                            ['F']
# previous_file_panel =                      ['H']               # lazyvim S
# file_panel_select_mode_items_select_down = ['J','shift+down']
# file_panel_select_mode_items_select_up =   ['K','shift+up']
# next_file_panel =                          ['L']               # lazyvim S
# create_new_file_panel =                    ['N']               # lazyvim S
# quit =                                     ['Q']
#
# Y: ctrl =====================================================================================================
# compress_file =             ['ctrl+a']          # archive
# cancel_typing =             ['ctrl+c', 'esc']
# page_down     =             ['ctrl+d']          # pgdown
# focus_on_metadata =         ['ctrl+m']          # lazyvim S
# focus_on_process_bar =      ['ctrl+p']          # lazyvim S
# focus_on_sidebar =          ['ctrl+s']          # lazyvim S
# page_up =                   ['ctrl+u']          # pgup
# close_file_panel =          ['ctrl+w']          # browser S
# extract_file =              ['ctrl+x']          # eXtract
# copy_path =                 ['ctrl+y']         
# ---------------------------------------------------------
# open_sort_options_menu =    ['alt+s']          # arrange
# pinned_directory =          ['alt+P']          # sidebar
# toggle_file_preview_panel = ['alt+f']          # lazyvim S
# toggle_reverse_sort =       ['atl+r']  


# sorting by their use.


#Y: Basic.
# parent_directory = ['h', 'left', 'backspace']
# confirm = ['l', 'enter']
# quit = ['Q']
#
# Y: Navigation 
# list_up = ['k']
# list_down = ['j']
# page_up = ['ctrl+u']   # pgup
# page_down = ['ctrl+d'] # pgdown
#
# Y: Panel
# create_new_file_panel = ['N'] # lazyvim S
# close_file_panel = ['ctrl+w'] # browser S
# next_file_panel = ['L']       # lazyvim S
# previous_file_panel = ['H']   # lazyvim S
#
# Y: Focus
# focus_on_process_bar = ['ctrl+p']      # lazyvim S
# focus_on_sidebar = ['ctrl+s']          # lazyvim S
# focus_on_metadata = ['ctrl+m']         # lazyvim S
# toggle_file_preview_panel = ['ctrl+F'] # lazyvim S
# toggle_footer = ['F']
#
# Y: NVIM
# open_file_with_editor = ['e']
# open_current_directory_with_editor = ['E']
#
# Y: FileManagement =================================================================== 
# file_panel_item_create = ['n'] # crete file  - a
# file_panel_item_rename = ['r'] # rename file - r
#
# copy_items = ['y']             # copy file   
# cut_items = ['x']              # cut file
# paste_items = ['p']            # pest file
# delete_items = ['d', 'delete'] # delete file
#
# toggle_dot_file = ['.']
# pinned_directory = ['ctrl+P']
# change_panel_mode = ['v']
# open_help_menu = ['?']
# open_command_line = [':']
# copy_path = ['ctrl+y']
# copy_present_working_directory = ['c']
# search_bar = ['/']
#
# G: RARE Use:
# extract_file = ['ctrl+x']           # eXtract
# compress_file = ['ctrl+a']          # archive
# open_sort_options_menu = ['ctrl+S'] # 
# toggle_reverse_sort = ['ctrl+R']    #
#
# Y: Edit (Typing hotkeys can conflict with all hotkeys)
# confirm_typing = ['enter']
# cancel_typing = ['ctrl+c', 'esc']
#
# B: Select Mode.
# file_panel_select_mode_items_select_down = ['J', 'shift+down']
# file_panel_select_mode_items_select_up = ['K', 'shift+up']
# file_panel_select_all_items = ['A']
