# ============================================================================================================================
parent_directory = ['-', '']
confirm = ['enter', '']
quit = ['ctrl+c', '']        # also know as, theprimeagen troller
# Y: Navigation
list_up = ['k', '']
list_down = ['j', '']
page_up = ['pgup', '']
page_down = ['pgdown', '']

# Y: file manager 
file_panel_item_create = ['a', '']
file_panel_item_rename = ['r', '']

copy_items = ['y', '']
cut_items = ['x', '']
paste_items = ['p', '']
delete_items = ['d', '']

toggle_dot_file = ['.', '']
pinned_directory = ['P', '']
change_panel_mode = ['m', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
copy_path = ['Y', '']
copy_present_working_directory = ['c', '']
search_bar = ['/', '']

# Y: Panel
create_new_file_panel = ['n', '']
close_file_panel = ['q', '']
next_file_panel = ['tab', '']
previous_file_panel = ['shift+tab', '']

# Y: Focus
focus_on_process_bar = ['ctrl+p', '']
focus_on_sidebar = ['ctrl+s', '']
focus_on_metadata = ['ctrl+d', '']
toggle_file_preview_panel = ['f', '']
toggle_footer = ['ctrl+f', '']

# Y: NVIM
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']

# other
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['esc', '']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['J', '']
file_panel_select_mode_items_select_up = ['K', '']
file_panel_select_all_items = ['A', '']


# G: rare use
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']

open_sort_options_menu = ['o', '']
toggle_reverse_sort = ['R', '']
